Format: 1A

# Polls

Polls is a siomple _API_ for testing API Blueprint on [Apiary](http://apiary.io)

# Group Questions

Questions asked in the poll.

## Questions [/questions/?max_count={mc}&year={year}]

+ Parameters

    + mc: `100` (number, required) - Maximum number of questions to return
    
    + year: `2016` (number, optional) - Year when the question was asked

### List all questions [GET]

Get a list of all questions *ever* asked in the universe.

And the answers to them!

+ Response 200 (application/json)

        {
            "questions": [
                {
                    "id": 1,
                    "q": "What is life?",
                    "a": "We don't really know."
                },
                {
                    "id": 2,
                    "q": "What is the meaning of lifew?",
                    "a": "42."
                }
            ]
        }
        
### Create a question [POST]

Create a brand new question. You have to supply question and answer.

+ Request (application/json)

        {
            "q": "Is a tomato a vegetable?",
            "a": "No, it's a fruit."
        }
        
+ Response 201 (application/json)

    + Headers
    
            Location: /questions/3
        
    + Body
    
            {
                "id": 3,
                "q": "Is a tomato a vegetable?",
                "a": "No, it's a fruit."
            }

## Question [/questions/{id}]

A single question.

+ Parameters
    + id (number) - Question ID

### Get full details of a question [GET]

+ Response 200 (application/json)

        {
            "q": "What is the capital of Germany?",
            "a": "Berlin"
        }
        
### Edit an existing question [PUT]

+ Request (application/json)

        {
            "q": "What is Germany's capital called?"
        }
        
+ Response 204

+ Request (application/json)

        {
            "a": "It is called Berlin"
        }
        
+ Response 204

+ Request (application/json)

        {
            "q": "What is Germany's capital called?",
            "a": "It is called Berlin"
        }
        
+ Response 204
        

### Create a new question [POST]

+ Request (application/json)

    + Headers
    
            X-Auth-Token: 56tfgh456fs78
            Z-Tunnelling: 56
            
    + Body
    
            {
                "q": "What is the capital of France?",
                "a": "Paris"
            }

+ Response 201 (application/json)
 
    + Headers
    
            Location: /questions/5
            
    + Body
   
            {
                "id": 5,
                "q": "What is the capital of France?",
                "a": "Paris"
            }
            
### Delete a question [DELETE]

+ Response 204